export const CATEGORIES = ["PROPIEDADES", "EMPRENDIMIENTOS"];

export const OPERATION_STATUSES = [
  "EN_VENTA",
  "EN_ALQUILER",
  "ALQUILER_TEMPORARIO",
  "EN_CONSTRUCCION",
  "EN_POZO",
  "LISTO_PARA_VIVIR"
];

export const CURRENCIES = ["USD", "ARS"];

export const PUBLICATION_STATUSES = [
  "DISPONIBLE",
  "VENDIDO",
  "NO_DISPONIBLE",
  "ALQUILADO",
  "RESERVADO",
  "BORRADOR"
];
